### PR TITLE
Improvements on themes section

### PR DESCRIPTION
**Pull request by hbugdoll**

### CODE REVIEW

**Comment by nadar** [comment]
Thank you so much!

The documentation is such an important part of a Software and each improvement and change, even just a word, is very welcome! Sometimes its hard for us to explain things, which are clear to us, but maybe not  for others. Therefore please extend the guide, add new sections or ask us, so we can improve together. :+1:

**Comment by hbugdoll** [comment]
@nadar I totally agree with you! Thank you very much for your great piece of software.
Going forward, I will incorporate some of my/our Luya experiences into the guide pages.

**Comment by nadar** [comment]
@hbugdoll This would be great. I think there are quite a few sections which are hard to understand - or the informations is available but not at the location where people expecting/looking for that.

**Comment by boehsermoe** [comment]
@hbugdoll Thank you 👍

**Pull request merged**
