### PR TITLE
Wording + minor improvements

### PR DESCRIPTION
**Pull request by hbugdoll**
### What are you changing/introducing

wording according to wording list
plus some minor improvements

### CODE REVIEW

**Comment by nadar** [comment]
Hey @hbugdoll - okay this is just amazing! Wow

Thanks for make the guide so much more consistent - i can't wait to publish those changes into production!

**Comment by nadar** [comment]
Let me know if the PR is ready, you can change the PR to draft - otherwise i think its finished and ready to merge.

**Comment by hbugdoll** [comment]
@nadar PR is ready for merge!

**Comment by nadar** [comment]
@hbugdoll even do this is already oftopic, i think we should write `Active Windows` instead of `ActiveWindows`. What do you think?

**Comment by hbugdoll** [comment]
My suggestion would be:
"Active Xyz" and "Active Xyzs" as proper names (contrary to the Yii documentation) and `ActiveXxx` if related to source code.

+ Active Button / Active Buttons / `ActiveButton`
+ Active Form / Active Forms / `ActiveForm`
+ Active Record / Active Records / `ActiveRecord`
+ Active Selection / Active Selections / `ActiveSelection`
+ Active Window / Active Windows / `ActiveWindow`

**Comment by nadar** [comment]
Yes i totally agree her 👍

**Pull request merged**
