### PR TITLE
remove overflow scroll for mobil screens fix #1409

### LINKED ISSUE #1409: iPad Chrome Overflow(?) Issues
iPad Chrome: We have experience very strange behaviors on iPad with chrome: sometimes it scrolles inside the curd, sometimes not, sometimes the mobile nav is static on top, sometimes not... maybe test with a real device. flexbox related?

I assume its a problem with the overflow:hidden. This should be disabled on mobile devices as you can make touch gestures every where.

### PR DESCRIPTION
**Pull request by dev7ch**
### What are you changing/introducing

.luya-content css class, enable overflow-y from $nav-breakpoint

### What is the reason for changing/introducing

#1409 

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes

### CODE REVIEW

**Comment by nadar** [comment]
@TheMaaarc could you please review/confirm/merge this PR? As i am not sure it will break existing expected behaviors in other browsers.

**Comment by dev7ch** [comment]
ok, the `height` from `.luya` is removed.

i was asking myself, in that case, does it make sense to have the height here?

https://github.com/dev7ch/luya/blob/bb6110d2439f83b99196c6fe536b11002e35ff6a/modules/admin/src/resources/scss/components/_luya.scss#L18

and here:
https://github.com/dev7ch/luya/blob/bb6110d2439f83b99196c6fe536b11002e35ff6a/modules/admin/src/resources/scss/components/_luya.scss#L23

**Comment by TheMaaarc** [comment]
The height 100% is mostly necessary because of flexbox. It's hard to say if it still is or not - would have to test that.

**Comment by dev7ch** [comment]
can we merge this?

**Comment by nadar** [comment]
@dev7ch i am going to merge as @TheMaaarc has approved the PR.

**Pull request merged**
