### PR TITLE
Bugfix: No Login loaded

### PR DESCRIPTION
**Pull request by boehsermoe**
login.js thow exception because jQuery was loaded defered (after the login.js)

### CODE REVIEW

**Comment by nadar** [comment]
I am unable to reproduce this problem, could please post more informations? 

@TheMaaarc  Maybe this is related to https://github.com/luyadev/luya/commit/0b176ef937db9e204ec0fdf1488b8470362c34df ?

**Comment by boehsermoe** [comment]
I used mac os with chrome browser. The jQuery will be load in the body-end `<script src="/assets/bd831c40/jquery.js" defer="defer"></script>` but the login.js and inline JS will be execute before the jquery.js (in consequence of the defer attribute).
So the jQuery is not available when login.js and inline JS is executing.

**Comment by nadar** [comment]
And this is the default behavior from the latest dev-master kickstarter? Did you made changes in the config for your asset manager or bundles? Cause i do not have the defer option in my files.

envs/dev screenshot:

bildschirmfoto 2017-11-09 um 09 18 27

**Comment by boehsermoe** [comment]
Oh yeah sorry. I added defer to the jsOptions in JqueryAsset config. It is a simple possibility to get a bit faster page load. If the registerJs will be load on body end, it works fine anyway.

**Comment by nadar** [comment]
But its not in jQuery ready function anymore. POS_END does not create the `jQuery(document).ready()` wrapper.

**Comment by dev7ch** [comment]
Hello @boehsermoe after having a quick closer look at the login loading issue, I realized there is stuff which should be tied up.

For now, I made a fix (not deeply tested) which loads can load login `async` or `defer`.

the loading is configured in the config file under components > assetManager.

@nadar  what u mean with POS_END, i am using POS_LOAD?

**Comment by dev7ch** [comment]
@nadar we need the window on load handler e.g. for the floating labels

**Comment by dev7ch** [comment]
example config:

```php
'components' => [
 //...
        'assetManager' => [
            'bundles' => [
                'luya\admin\assets\Login' => [
                    'jsOptions' => [
                        //'defer' => 'defer'
                        'async' => 'async'
                    ],
                    'depends' => ['yii\web\JqueryAsset'],
                ],
                'yii\web\JqueryAsset' => [
                    'jsOptions' => [
                        //'defer' => 'defer'  // not working at the moment
                    ],
                ],
            ],
        ],
    ],

```

**Comment by nadar** [comment]
@dev7ch i don't understand what you are trying to say. 

Defer and Async properties are commonly used to increase page speed in frontend situations, therefore we do not have to take care of this in admin login, but of course if someone configures this options for the jquery bundle, the admin login should still work.

**Comment by dev7ch** [comment]
I mean with the commit in the branch mentioned above it is possible to load e.g. `login.js` async or defer.

jquery async is not possible at the moment.

**Comment by nadar** [comment]
We have to close this PR as the files as been moved to its dedicated modules.

**Pull request closed without merging**
