### PR TITLE
adjust icon and toast positions fix #1486

### LINKED ISSUE #1486: Large Success Toast
When a toast message with a large message is displayed, the icon is wrong positioned.

image

### PR DESCRIPTION
**Pull request by dev7ch**
### What are you changing/introducing

#1486

### What is the reason for changing/introducing

#1486

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes

### CODE REVIEW

**Comment by nadar** [comment]
@dev7ch Your screenshot still shows the icon problem, why? Sure i am going to implement the close function.

**Comment by dev7ch** [comment]
Yes, the screenshot shows the old toast, why we need a position fixed for toast, its not sticked to the bottom

**Comment by dev7ch** [comment]
image
this is how the fixed toast looks like (without close icon)

**Comment by nadar** [comment]
looks good, thanks, i am going to add the close function after the merge.

**Comment by dev7ch** [comment]
great

**Pull request merged**
