### PR TITLE
Improve design for admin zone

### PR DESCRIPTION
**Pull request by phongtt3**
I not sure i love Yii2 & Angular, but i like the idea behind Luya a lots, here is my suggestion about new design for admin zone, pls check.
Thank

screen shot 2017-04-12 at 15 04 12

### CODE REVIEW

**Comment by TheMaaarc** [comment]
Will have a look at your suggestion and get back to you. Thanks.

**Comment by nadar** [comment]
I like the idea of the left menu, but i am not yet happy with this green color. I think there should be also somewhere the orange color from the logo which is also used in the frontend when the toolbar is enabled (the lash at the right top)

**Comment by nadar** [comment]
Maybe using similar colors like on: https://luya.io/

Anyhow, thanks @phongtt3 for sharing your ideas and taking time, we appreciate this a lot.

**Comment by phongtt3** [comment]
Try a new option with orange color from material design palette.
- ref https://material.io/color/#!/?view.left=0&view.right=0&primary.color=ff9800&primary.text.color=000000
screen shot 2017-04-12 at 21 39 27

**Comment by nadar** [comment]
The screenshot looks good - i like the colors! 

+ The Active Link for the Top Menu Bar (Module Bar) should mabye indicate the active state more clear and not just a text decoration underline, any ideas?
+ There is large margin/padding between the menu on the left and the content on right - maybe this should look the same on each edge of the content (15px15px15px15px or sth like this)
+ What does the content mangement system looks like? (Page Content)

Thanks for the work! looking forward to see more changes.

**Comment by phongtt3** [comment]
Thanks for comments, here's new look, i think it's pretty cool. But seem to be need major efforts
 to update entire site with new consistence colors palette.
Why don't you guys used color variable :((

screen shot 2017-04-13 at 10 04 26
screen shot 2017-04-13 at 10 04 34

**Comment by nadar** [comment]
@phongtt3 Sorry for the late response. I have tested your design ideas and i saw a lot of bugs. I am not happy with the yellow color, now it seems that there are so many different colors and different backgrounds, black, white, yellow, black font on yellow, white font on yellow, blue buttons, grey background, blue-grey-sidebar... and so on

bildschirmfoto 2017-04-17 um 13 26 52

I still like the idea of the UI improvement for the Sidebar menu on the left. On a first step it would be cool to just keep the original colors and improve the sidebar, like you did. So it could be a step by step improvement. I really would like to merge your ideas as i appreciate when people taking time to work on open source projects

**Comment by nadar** [comment]
@phongtt3 We are working on admin ui improvement, there is a new repo with some drafts, maybe you have ideas or inputs. 

https://github.com/luyadev/admin-ui-redesign

**Comment by phongtt3** [comment]
Okay, thank for your invitation. So will checkout soon and have a look

**Pull request closed without merging**
