### PR TITLE
Vietnamese translate

### PR DESCRIPTION
**Pull request by vuongminh**
Vietnamese translate:

+ Admin Module
+ CMS Admin Module
...

### CODE REVIEW

**Comment by nadar** [comment]
It seems like your previous commits has been added to this PR. Maybe update your master branch and create new branch for the translations and then send a PR?

**Comment by vuongminh** [comment]
Okay. :D

**Comment by nadar** [comment]
We have added a rebasemaster script you can run to rebase your master branch `./scripts/rebasemaster.sh init`.

**Comment by nadar** [comment]
https://luya.io/guide/luya-collaboration#rebase-your-master

**Pull request closed without merging**
