### PR TITLE
Fix php 5.6 issue

### PR DESCRIPTION
**Pull request by vuongminh**
Fix php 5.6 parser error when call static method tableName() of modelClass.

### CODE REVIEW

**Comment by nadar** [comment]
Thanks. I think instead of creating a temp variable $this->modelClass->tableName would work to?

**Comment by vuongminh** [comment]
No it wouldn't work when it's string.

**Comment by nadar** [comment]
Maybe its possible to add a small unit test?

**Comment by vuongminh** [comment]
Yes i am creating now!

**Comment by nadar** [comment]
Well done! Thanks

**Pull request merged**
