### PR TITLE
Brazilian translations

### PR DESCRIPTION
**Pull request by rodzadra**

### CODE REVIEW

**Comment by nadar** [comment]
@rodzadra let me know if you need help organizing your pull request, i would love to see your translations in the upcoming release!

**Comment by rodzadra** [comment]
@nadar 
Sorry for the late answer. I just committed the kickstarter file.
If you have any other file to be translated into Brazilian Portuguese, please let me know.
thank you.

**Comment by nadar** [comment]
@rodzadra Looks great! Would be great to see the last core modules translated as well:

- [ ]  https://github.com/luyadev/luya/tree/master/modules/crawler/src/admin/messages
- [ ]  https://github.com/luyadev/luya/tree/master/modules/errorapi/src/messages
- [ ]  https://github.com/luyadev/luya/tree/master/modules/news/src/admin/messages
- [ ]  https://github.com/luyadev/luya/tree/master/modules/gallery/src/admin/messages

**Comment by rodzadra** [comment]
@nadar 

￼ https://github.com/luyadev/luya/tree/master/modules/crawler/src/admin/messages
￼ https://github.com/luyadev/luya/tree/master/modules/errorapi/src/messages
￼ https://github.com/luyadev/luya/tree/master/modules/news/src/admin/messages
￼ https://github.com/luyadev/luya/tree/master/modules/gallery/src/admin/messages

Were translated.

**Comment by nadar** [comment]
@rodzadra it seems like the admin module translations file is missing.

**Pull request merged**
