### PR TITLE
disable -moz-scrollbars-none, fix #1454

### LINKED ISSUE #1454: In new admin UI mouse scrolling in Mozilla Firefox does not work
In new admin UI mouse scrolling in Mozilla Firefox does not work

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | RC4
| Mozilla Firefox Version     | 55
| Operating system | Windows

### PR DESCRIPTION
**Pull request by dev7ch**

### CODE REVIEW

**Comment by dev7ch** [comment]
testing reqiured, works on FF Version 55.0.3 (64-Bit) iMac

**Comment by nadar** [comment]
@dev7ch would you please so kind to test those changes in existing browsers?

**Comment by dev7ch** [comment]
its tested in, FF Version 55.0.3, chrome, safari and Opera (newest Versions)

**Comment by nadar** [comment]
@dev7ch perfect, please add a changelog entrie in the fixed section

**Comment by dev7ch** [comment]
its tested in the above listed version.
it would be glad if you can add this, i dunno where u mean, and i am leaving right now.
thanks for your support.

**Comment by nadar** [comment]
sure @dev7ch, this is what i meant: https://github.com/luyadev/luya/blob/master/CHANGELOG.md#fixed

**Pull request merged**
