### PR TITLE
Update app-menu.md

### PR DESCRIPTION
**Pull request by hbugdoll**
minor improvements

### CODE REVIEW

**Comment by hbugdoll** [comment]
One shouldn't use `Yii::$app->menu->current` inside blocks, right?
It obviously points to the homepage.

**Comment by nadar** [comment]
Current should always Point to the current menu item, while homepage points to the homepage. If current always points to the same page, i think its due to caching of the block itself

**Comment by nadar** [comment]
Thanks for the text update @hbugdoll once again!

**Comment by hbugdoll** [comment]
> Current should always Point to the current menu item, while homepage points to the homepage. If current always points to the same page, i think its due to caching of the block itself

I was not precisely enough in usage of `current`.
And after some research it becomes clearer:

`Yii::$app->menu->current` points to the current menu item in frontend, but not inside backend's `admin()`.
In this case `Menu::resolveCurrent()` calls `Menu::getHome()`:
https://github.com/luyadev/luya-module-cms/blob/a2697808f1ac261dbad79594138b5807e8ec942d/src/Menu.php#L522-L532

**Pull request merged**
