### PR TITLE
Adjusted LazyLoad to use an options array for `alt` and `title` attri…

### LINKED ISSUE #2031: LazyLoad cannot be used with alt and title attributes
### What steps will reproduce the problem?
Use luya\lazyload\LazyLoad and set "alt" and "title" attributes

### What is the expected result?
LazyLoad working with "alt" and "title" attributes

### What do you get instead?
Not working

### PR DESCRIPTION
**Pull request by JohnnyMcWeed**
### What are you changing/introducing
LazyLoad options array for e. g. `alt` and `title` tag.

### What is the reason for changing/introducing
[#2031](https://github.com/luyadev/luya/issues/2031)

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | I hope so
| Fixed issues  | this closes #2031

### CODE REVIEW

**Comment by nadar** [comment]
For whatever reason code climate does not post the coverage.

**Comment by JohnnyMcWeed** [comment]
> For whatever reason code climate does not post the coverage.

Do I need to do something?

**Comment by nadar** [comment]
A unit test would be nice :-) (but in terms of code climate you can't do anything, even the github actions says `Test report uploaded successfully to Code Climate`)

**Comment by nadar** [comment]
Thanks!

**Pull request merged**
